[toolchain]
anchor_version = "1.0.2"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
magican_token = "EaQA46S3p1opE1Q4oNTh7xpresSTvuNDa9NSJMbXj5YB"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha"

[hooks]
