[toolchain]
anchor_version = "1.0.2"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
magican_token = "BcyHy9xz3kvthmvc2WFQRYGoFfzCAQcpLxVC7d1zPjQD"
#[programs.devnet]
#magican_token = "BcyHy9xz3kvthmvc2WFQRYGoFfzCAQcpLxVC7d1zPjQD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"


[scripts]
test = "npx mocha"

[hooks]
